name: CI/CD for React App

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: Window-latest

    steps:
      # Step to checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

     # Step to set up Node.js.
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

     # Step to install dependencies.
      - name: Install dependencies
        run: npm install

     # Step to run tests
      - name: Build Project
        run: npm run build
        env:
            TEXT: ${{vars.TEXT}}  

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: test
          folder: build